try:
    from typing import Protocol
except ImportError:
    from typing_extensions import Protocol
from typing import List, Optional
from uuid import UUID
from domain.entities.user import User
from domain.entities.pattern import Pattern
from domain.entities.collection import Collection
from domain.entities.user_pattern import UserPattern

class IUserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> Optional[User]: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...

class IPatternRepository(Protocol):
    async def get_all(self, collection_id: Optional[UUID] = None) -> List[Pattern]: ...
    async def get_by_id(self, pattern_id: UUID) -> Optional[Pattern]: ...
    async def get_collections(self) -> List[Collection]: ...

class IFavoriteRepository(Protocol):
    async def get_count_for_user(self, user_id: UUID) -> int: ...
    async def get_by_user_and_pattern(self, user_id: UUID, pattern_id: UUID) -> Optional[UserPattern]: ...
    async def add(self, favorite: UserPattern) -> None: ...
    async def update(self, favorite: UserPattern) -> None: ...
    
    # Idempotency storage (Storage of correlation_id using repository/storage)
    async def exists_correlation_id(self, correlation_id: str) -> bool: ...
    async def register_correlation_id(self, correlation_id: str) -> None: ...
